# coding: utf-8
"""Client-side private config.

Generated by `bigqmt-init`.
DO NOT COMMIT: this file holds an account id and Redis credentials.
"""

BIGQMT_ACCOUNT_ID = '31292575'
BIGQMT_RPC_TIMEOUT_SECONDS = 30.0

BIGQMT_REDIS_CONFIG = {
    "transport": 'redis',
    "host": '127.0.0.1',
    "port": 6379,
    "db": 5,
    "username": '',
    "password": '',
}

# Reference/history reads go straight to Big QMT's FormulaServer (port
# 58600) instead of over RPC. Every miss falls back to RPC, so an
# unreachable 58600 changes nothing.
BIGQMT_FORMULA_SERVER_CONFIG = {
    "enabled": True,
}

BIGQMT_LOCAL_CACHE_CONFIG = {
    "enabled": True,
    "dir": None,
    "fallback_rpc": True,  # MiniQMT-compatible adjusted reads; False = offline only
    "format": "auto",
}
